# This workflow is provided for testing changes to the action.
# When developing make sure that "Scan 2 - failing" produces expected kube-linter validation logs.

name: kube-linter-action development self-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-scan:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        format: [ sarif, plain, json ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: 1.1 - Scan - should succeed
        uses: ./
        with:
          directory: sample/valid-yaml
          config: sample/.kube-linter-config.yaml

      ## Fails currently due to https://github.com/stackrox/kube-linter/issues/213
      ## TODO: enable once the above is addressed
      #- name: 1.1 - Upload SARIF output file to GitHub
      #  uses: github/codeql-action/upload-sarif@v1
      #  with:
      #    sarif_file: kubelinter.log

      - name: 1.2 - Scan - should succeed - specific format
        uses: ./
        with:
          directory: sample/valid-yaml
          config: sample/.kube-linter-config.yaml
          format: ${{ matrix.format }}

      - name: 2.1 - Scan - should fail
        uses: ./
        with:
          directory: sample/invalid-yaml
          config: sample/.kube-linter-config.yaml
        continue-on-error: true

      - name: 2.1 - Upload SARIF output file to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: kubelinter.log

      - name: 2.2 - Scan - should fail - specific format
        uses: ./
        with:
          directory: sample/invalid-yaml
          config: sample/.kube-linter-config.yaml
          format: ${{ matrix.format }}
        continue-on-error: true
